modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/TCBuildMC/BlockyLib/issues"
license = "Apache-2.0"

[[mods]]
modId = "blockylib"
version = "${version}"
displayName = "Blocky Lib Mod"
authors = "TCBuildMC"
credits = "Block_Mrlimr267"
displayURL = "https://github.com/TCBuildMC/BlockyLib"
description = '''
A library Minecraft mod. Just provides useful tools and extends Architectury Api.
'''
logoFile = "icon.png"

[[dependencies.blockylib]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockylib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockylib]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
